/*++

Module Name:

    device.c - Device handling events for example driver.

Abstract:

   This file contains the device entry points and callbacks.
    
Environment:

    Kernel-mode Driver Framework

--*/

#include "driver.h"
#include "device.tmh"

#ifdef ALLOC_PRAGMA
#pragma alloc_text (PAGE, RoboBusCreateDevice)
#endif


NTSTATUS
RoboBusCreateDevice(
    _Inout_ PWDFDEVICE_INIT DeviceInit
    )
/*++

Routine Description:

    Worker routine called to create a device and its software resources.

Arguments:

    DeviceInit - Pointer to an opaque init structure. Memory for this
                    structure will be freed by the framework when the WdfDeviceCreate
                    succeeds. So don't access the structure after that point.

Return Value:

    NTSTATUS

--*/
{
    WDF_OBJECT_ATTRIBUTES   attributes;
	FDO_DEVICE_CONTEXT* context;
    WDFDEVICE device;
    NTSTATUS status;

    PAGED_CODE();

	WdfDeviceInitSetDeviceType( DeviceInit, FILE_DEVICE_BUS_EXTENDER );
	WdfDeviceInitSetExclusive( DeviceInit, TRUE );

	WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE( &attributes, FDO_DEVICE_CONTEXT );

    status = WdfDeviceCreate( &DeviceInit, &attributes, &device );


    if( NT_SUCCESS(status) )
	{
        //
        // Get a pointer to the device context structure that we just associated
        // with the device object. We define this structure in the device.h
        // header file. DeviceGetContext is an inline function generated by
        // using the WDF_DECLARE_CONTEXT_TYPE_WITH_NAME macro in device.h.
        // This function will do the type checking and return the device context.
        // If you pass a wrong object handle it will return NULL and assert if
        // run under framework verifier mode.
        //
        context = GetFdoContext( device );

		WDF_OBJECT_ATTRIBUTES_INIT( &attributes );
		attributes.ParentObject = device;
		status = WdfWaitLockCreate( &attributes, &context->ChildLock );
	}

	if( NT_SUCCESS(status) )
	{

        //
        // Create a device interface so that applications can find and talk
        // to us.
        //
        status = WdfDeviceCreateDeviceInterface( device, &GUID_DEVINTERFACE_RoboBus, NULL );
	}

	if( NT_SUCCESS(status) )
	{
        //
        // Initialize the I/O Package and any Queues
        //
        status = RoboBusQueueInitialize(device);
    }

	if( NT_SUCCESS(status) )
	{
		PNP_BUS_INFORMATION busInfo;
		busInfo.BusTypeGuid = GUID_DEVCLASS_ROBOT;
		busInfo.LegacyBusType = PNPBus;
		busInfo.BusNumber = 0;
		WdfDeviceSetBusInformationForChildren( device, &busInfo );

	}

    return status;
}


